
image: 
  - Visual Studio 2017
  - Ubuntu

environment:
  matrix:
    - NODE_ENV": development
    - NODE_ENV": production

stack: node 8

install:
  - npm install

build: off

test_script:
  - npm run eslint
  - ./node_modules/.bin/nyc npm test


cache:
- node_modules -> package.json
