
image: 
  - Visual Studio 2017
  - Ubuntu

environment:
    COVERALLS_SERVICE_NAME: appveyor
    COVERALLS_REPO_TOKEN:
        secure: ZYdATrcqk4WYd2UPNvdhUdDNKIvFdodts9+F2gnAhVomCbp4G5pWCGQZSVw/Kutc
    matrix:
    - NODE_ENV: development
    - NODE_ENV: production

stack: node 8

install:
  - npm install
  - npm install mocha-appveyor-reporter coveralls

build: off

test_script:
  - npm run eslint
  - ./node_modules/.bin/nyc --lines 95 npm test -- --reporter mocha-appveyor-reporter
  - ./node_modules/.bin/nyc report --reporter=text-lcov | ./node_modules/.bin/coveralls


cache:
- node_modules -> package.json
