
image: 
  - Visual Studio 2017
  - Ubuntu

install:
  - npm install

build: off

test_script:
  - cmd: npm run eslint
  - cmd: ./node_modules/.bin/nyc npm test
  - sh: npm test

cache:
#- node_modules -> package.json
