language: node_js
env:
  matrix:
    - NODE_ENV: development
    - NODE_ENV: production
node_js:
- 11
- 10
- 8
cache: npm
branches:
  except:
  - dev-wia
before_install:
- python ./version.py
- npm i -g npm@5.6.0
install:
- npm install
- npm install --only=dev
- npm install coveralls codecov nyc
script:
- npm run cov-test
- ./node_modules/.bin/nyc report --reporter=text-lcov > coverage.lcov && codecov
after_script: 
deploy:
- provider: npm
  email: info@mediagoom.com
  skip_cleanup: true
  api_key:
    secure: DhAAwfpRg5T3Nsl84wzYYpUdHEQM5AshD0lH3bral7dKgv2KMpn97LGcjyLEMb8FgUSTu/ARoVgnwCggSnLFbDBl7ulUdPEQ+GH+N0jn7pJAaoCCoPIHV09hdSl/tIWQ11qWxwaxSGqRmbKShV4luzGu19VKw46ScPxcQGmyoKT3x8qiUPfJzVvitRO8Pt9Sp5o5CFwGO3lBKfDac0Jk/Em64gyAE/BsNX1DNvZPa3MUC6okQD9PGMZlu891g1ZRMNEncRdCuwUyMxRhcnziQD6/Mp74vIsInjDeI/hop1NFEgkG/4RQP3fuDHS+s5WZ3XlSixBsVmfS1jHKnVU9mChiDk7kb05mMfHPpvmCQJF6kuQu1R+GAdafYvs9RNh19wZNcfghrI0I+LvXXE1NsAk81G99bHa4ir06IHrsBsR5ITijpWnEiIGgMlMcnXzZeCCxoNFe3JBd4ISKVv7uqgyshrJSzd3IHex/TFgtxBtiqZIiipMUcZWeFh8PkoP+7SGo8QmtP+LUnbFUtmegvWevFIUDGRLVr55J2hFHa/r6QRv4INlxaV67z7IPDjs5qdoZRRrS8ctDm7opAcTAjGb9ohb64RUnnLyBBT833WyYIc8CBbZ6F4r9rmJRNxihFuxvFl12YXR8D9iqAGRGzrgqB3EYkIGMfs+1mr0snIw=
  on:
    tags: true
    repo: mediagoom/opflow
    node: 10
